---
title: "Stat_Project"
output:
  pdf_document: default
  html_document: default
---

```{r setup}
library(tidyverse)
library(knitr)
library(hoopR)
library(rvest)
library(stringr)
library(stringi)

knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
rawgamelogs <- load_nba_player_box(seasons = 2025)

library(dplyr)

team_totals <- rawgamelogs %>%
  group_by(game_id, team_id) %>%
  summarise(
    team_FGA = sum(field_goals_attempted, na.rm = TRUE),
    team_FTA = sum(free_throws_attempted, na.rm = TRUE),
    team_TOV = sum(turnovers, na.rm = TRUE),
    team_minutes = sum(minutes, na.rm = TRUE)
  )

rawgamelogs2 <- rawgamelogs %>%
  left_join(team_totals, by = c("game_id", "team_id"))

rawgamelogs2 <- rawgamelogs2 %>%
  mutate(
    USG = 100 *
      (field_goals_attempted + 0.44 * free_throws_attempted + turnovers) *
      team_minutes /
      ((team_FGA + 0.44 * team_FTA + team_TOV) * 5 * minutes)
  )

rawgamelogs2 <- rawgamelogs2 %>%
  filter(minutes > 0) %>%
  filter(USG < 100)

```

```{r import_data, include=FALSE}


GameLogs <- rawgamelogs2 %>% 
  dplyr::select(
    game_id, game_date, home_away, athlete_display_name, team_display_name,
    opponent_team_display_name, three_point_field_goals_made, minutes, points,
    assists, rebounds, steals, blocks, turnovers, fouls, starter, season_type,
    athlete_position_abbreviation, USG
  ) %>%
  rename(
    GameNo = game_id,
    Date = game_date,
    Location = home_away,
    Name = athlete_display_name,
    Team = team_display_name,
    Opponent = opponent_team_display_name,
    FG3M = three_point_field_goals_made,
    Minutes = minutes,
    Points = points,
    Assists = assists,
    Rebounds = rebounds,
    Steals = steals,
    Blocks = blocks,
    TO = turnovers,
    PF = fouls,
    Starter = starter,
    SeasonType = season_type,
    Position = athlete_position_abbreviation,
    USG = USG
  ) %>%
  mutate(
    FantasyPoints = Points + 1.2 * Rebounds + 1.5 * Assists +
                    3 * Steals + 3 * Blocks - TO
  ) %>% na.omit()
```

```{r}
plot_data <- GameLogs %>%
  filter(
    !is.na(FantasyPoints),
    !is.na(Minutes),
    !is.na(Points),
    !is.na(Rebounds),
    !is.na(Assists),
    !is.na(USG)
  )
```

```{r}
methods_table <- tibble(
  Variable = c("FantasyPoints", "Minutes", "Points", "USG", "Rebounds", "Position"),
  Meaning = c(
    "Overall player performance score",
    "Minutes played in the game",
    "Points scored in the game",
    "Usage Rate",
    "Number of rebounds",
    "Player position"
  ),
  Units = c(
    "Points",
    "Minutes",
    "Points",
    "Percentage",
    "Count",
    "Category"
  ),
  Min = c(
    min(plot_data$FantasyPoints, na.rm = TRUE),
    min(plot_data$Minutes, na.rm = TRUE),
    min(plot_data$Points, na.rm = TRUE),
    min(plot_data$USG, na.rm = TRUE),
    min(plot_data$Rebounds, na.rm = TRUE),
    NA
  ),
  Max = c(
    max(plot_data$FantasyPoints, na.rm = TRUE),
    max(plot_data$Minutes, na.rm = TRUE),
    max(plot_data$Points, na.rm = TRUE),
    max(plot_data$USG, na.rm = TRUE),
    max(plot_data$Rebounds, na.rm = TRUE),
    NA
  ), 
  Median = c(
    median(plot_data$FantasyPoints, na.rm = TRUE),
    median(plot_data$Minutes, na.rm = TRUE),
    median(plot_data$Points, na.rm = TRUE),
    median(plot_data$USG, na.rm = TRUE),
    median(plot_data$Rebounds, na.rm = TRUE),
    NA
  ),
  Std = c(
    sd(plot_data$FantasyPoints, na.rm = TRUE),
    sd(plot_data$Minutes, na.rm = TRUE),
    sd(plot_data$Points, na.rm = TRUE),
    sd(plot_data$USG, na.rm = TRUE),
    sd(plot_data$Rebounds, na.rm = TRUE),
    NA
  )
)

methods_table
```

```{r, width  =5,  height = 5}
mean_fp <- mean(plot_data$FantasyPoints, na.rm = TRUE)
q25 <- quantile(plot_data$FantasyPoints, 0.25, na.rm = TRUE)
q75 <- quantile(plot_data$FantasyPoints, 0.75, na.rm = TRUE)
ggplot(plot_data, aes(x = FantasyPoints)) +
  geom_histogram(binwidth = 5, fill = "skyblue", color = "black") +
  geom_vline(xintercept = mean_fp, color = "red", linewidth = 0.5) +
  annotate("text", x = mean_fp, y = -10, label = "Mean", color = "red", angle = 0, vjust = -0.5) + 
  geom_vline(xintercept = q25, color = "darkgreen", linetype = "dashed") +
  annotate("text", x = q25, y = 0, label = "25%", color = "darkgreen", angle = 0, vjust = -0.5) +
  geom_vline(xintercept = q75, color = "darkgreen", linetype = "dashed") +
  annotate("text", x = q75, y = 0, label = "75%", color = "darkgreen", angle = 0, vjust = -0.5) +
  labs(
    title = "Distribution of Fantasy Points (2024-25)",
    x = "Fantasy Points",
    y = "Count"
  ) +
  theme_bw()


```

```{r, width = 5, height = 5}
mean_min <- mean(plot_data$Minutes, na.rm = TRUE)
q_25_min <- quantile(plot_data$Minutes, 0.25, na.rm = TRUE)
q_75_min <- quantile(plot_data$Minutes, 0.75, na.rm = TRUE)
ggplot(plot_data, aes(x = Minutes)) +
  geom_histogram(binwidth = 2, fill = 'skyblue', color = 'black')+
  geom_vline(xintercept = mean_min, color = 'red', linewidth = 0.5) +
  annotate('text', x = mean_min, y = 0, label = 'Mean', color = 'red', angle = 0, vjust = -0.5) +
  geom_vline(xintercept = q_25_min, color = 'darkgreen', linetype = 'dashed') +
  annotate('text', x = q_25_min, y = 0, label = '25%', color = 'darkgreen', angle = 0, vjust = -0.5) +
  geom_vline(xintercept = q_75_min, color = 'darkgreen', linetype = 'dashed') +
  annotate('text', x = q_75_min, y = 0, label = '75%', color = 'darkgreen', angle = 0, vjust= -0.5) +
  labs(title = 'Distribution of Minutes Played',
       x = 'Minutes Played',
       y = 'Count') +
  theme_bw()
```

```{r}
mean_usg <- mean(plot_data$USG, na.rm = TRUE)
q_25_usg <- quantile(plot_data$USG, 0.25, na.rm = TRUE)
q_75_usg <- quantile(plot_data$USG, 0.75, na.rm = TRUE)
ggplot(plot_data, aes(x = USG)) +
  geom_histogram(binwidth = 4, fill = 'skyblue', color = 'black')+
  geom_vline(xintercept = mean_usg, color = 'red', linewidth = 0.5) +
  annotate('text', x = mean_usg, y = 0, label = 'Mean', color = 'red', angle = 0, vjust = -0.5) +
  geom_vline(xintercept = q_25_usg, color = 'darkgreen', linetype = 'dashed') +
  annotate('text', x = q_25_usg, y = 0, label = '25%', color = 'darkgreen', angle = 0, vjust = -0.5) +
  geom_vline(xintercept = q_75_usg, color = 'darkgreen', linetype = 'dashed') +
  annotate('text', x = q_75_usg, y = 0, label = '75%', color = 'darkgreen', angle = 0, vjust= -0.5) +
  labs(title = 'Distribution of Usage Rate (%)',
       x = 'Usage Rate',
       y = 'Count') +
  theme_bw()
```

```{r, warning  = FALSE}

ggplot(plot_data, aes(x = Minutes, y = FantasyPoints, color = Location)) +
  geom_point(alpha = 0.3) +
  geom_smooth(method = "lm", color = "red") +
  labs(
    title = "Fantasy Points vs Minutes Played (2024-25)",
    x = "Minutes",
    y = "Fantasy Points"
  ) +
  theme_bw()
```

```{r}
ggplot(plot_data, aes(x = Position, y = FantasyPoints, fill = Starter)) +
  geom_boxplot(alpha = 0.7) +
  labs(
    title = "Fantasy Points by Position and Starter Status",
    x = "Position",
    y = "Fantasy Points",
    fill = "Starter"
  ) +
  scale_fill_manual(values = c("darkorange", "steelblue")) +
  theme_bw() +
  theme(
    legend.position = c(1, 1),        
    legend.justification = c(1, 1)
  )

```

```{r}
ggplot(plot_data, aes(x = Starter, y = FantasyPoints, fill = Starter)) +
  geom_boxplot(alpha = 0.7) +
  labs(
    title = "Fantasy Points for Starters vs Bench Players",
    x = "Starter Status",
    y = "Fantasy Points"
  ) +
  scale_fill_manual(values = c("darkorange", "steelblue")) +
  theme_minimal() +  
  theme(legend.position = "none")
```

```{r}
plot_data2 <- plot_data %>%
  mutate(Starter = ifelse(Starter == "TRUE", 1, 0))

ggplot(plot_data2, aes(x = FantasyPoints, y = Starter)) +
  geom_jitter(height = 0.05, width = 0.2, size = 2, alpha = 0.5) +
  geom_smooth(formula = y~x,method = 'glm', method.args = list(family = 'binomial'), se = FALSE,color = 'blue') +
  geom_hline(yintercept = mean(plot_data2$Starter), color = 'red') +
  annotate('text', x=  100, y = mean(plot_data2$Starter), label = "Mean", color = 'red', vjust = -0.5) +
  labs(title = 'FantasyPoints vs Starter',
       x = 'Fantasy Points',
       y = 'Starter') +
  scale_x_continuous(limits = c(-5, 100), breaks = seq(-5, 100,5)) +
  scale_y_continuous(limits = c(-0.05, 1.05), breaks = seq(-0.05, 1.05, 0.1)) +
  theme_bw()

```

```{r}
ggplot(data = plot_data, aes(x = USG, y = FantasyPoints)) +
  geom_point(alpha = 0.2) +
  geom_smooth(method = 'lm', se = FALSE) +
  labs(title = "Usage Rate VS Fantasy Points",
       x = "Usage Rate",
       y = "Fantasy Points") +
  theme_bw()
```

```{r}
over_5mins <- plot_data %>%
  filter(Minutes > 5) %>%
  na.omit()

ggplot(data = over_5mins, aes(x = USG, y = FantasyPoints, color = Starter)) +
  geom_point(alpha = 0.2) +
  geom_smooth(formula = y~x, method = 'lm') +
  labs(title = "Usage Rate vs Fantasy Points by Starter",
       subtitle = "Only players who played more than 5 mins",
       x = 'Usage Rate',
       y = 'Fantasy Points',
       color = "Starter") +
  scale_color_manual(values = c("darkorange", "steelblue")) + 
  theme_bw() +
  theme(
    legend.position = c(0, 1),        
    legend.justification = c(0, 1)
  )
  
```

```{r}

library(leaps)
library(boot)
library(broom)

predict_data <- GameLogs %>%
  dplyr::select(FantasyPoints, Minutes, USG, Starter, Position, Location, FG3M) %>%
  drop_na() %>%
  mutate(
    Starter = as.factor(Starter),
    Position = as.factor(Position),
    Location = as.factor(Location)
  )


full_model <- lm(
  FantasyPoints ~ Minutes + USG + Starter + Position + Location + FG3M,
  data = predict_data
)

summary(full_model)



```

```{r}
subset_fit <- regsubsets(
  FantasyPoints ~ Minutes + USG + Starter + Position + Location + FG3M,
  data = predict_data,
  nvmax = 6
)

subset_sum <- summary(subset_fit)

par(mfrow = c(1, 3))
plot(subset_sum$adjr2, type = "b", pch = 19,
     xlab = "Number of Predictors", ylab = "Adjusted R^2",
     main = "Best Subset: Adjusted R^2")

plot(subset_sum$bic, type = "b", pch = 19,
     xlab = "Number of Predictors", ylab = "BIC",
     main = "Best Subset: BIC")

plot(subset_sum$cp, type = "b", pch = 19,
     xlab = "Number of Predictors", ylab = "Cp",
     main = "Best Subset: Cp")

```

```{r}
best_bic_index <- which.min(subset_sum$bic)
best_bic_index

coef(subset_fit, best_bic_index)

```

```{r}
min_fp <- min(predict_data$FantasyPoints)

final_model <- lm(
  log(FantasyPoints - min_fp + 1) ~ Minutes + USG + Starter + Position,
  data = predict_data
)
```

```{r}
AIC(full_model)
BIC(full_model)
summary(full_model)$adj.r.squared

AIC(final_model)
BIC(final_model)
summary(final_model)$adj.r.squared
```

```{r}
par(mfrow = c(1, 1))
plot(final_model)

```

```{r}
set.seed(123)
fold_id <- sample(rep(1:10, length.out = nrow(predict_data)))

rmse_by_fold <- data.frame(Fold = integer(), RMSE = numeric())

for (k in 1:10) {
  train_data <- predict_data[fold_id != k, ]
  test_data  <- predict_data[fold_id == k, ]
  
  temp_model <- lm(formula(final_model), data = train_data)
  preds <- predict(temp_model, newdata = test_data)
  
  rmse_k <- sqrt(mean((test_data$FantasyPoints - preds)^2))
  
  rmse_by_fold <- rbind(rmse_by_fold,
                        data.frame(Fold = k, RMSE = rmse_k))
}

ggplot(rmse_by_fold, aes(x = factor(Fold), y = RMSE)) +
  geom_col(fill = "skyblue", color = "black") +
  labs(
    title = "10-Fold Cross-Validation RMSE",
    x = "Fold",
    y = "RMSE"
  ) +
  theme_bw()

```

```{r}
null_model <- lm(FantasyPoints ~ 1, data = predict_data)

discussion_table <- tibble(
  Model = c("Null Model", "Final Model"),
  RMSE = c(
    sqrt(mean(residuals(null_model)^2)),
    sqrt(mean(residuals(final_model)^2))
  ),
  R2 = c(
    summary(null_model)$r.squared,
    summary(final_model)$r.squared
  ),
  Adj_R2 = c(
    summary(null_model)$adj.r.squared,
    summary(final_model)$adj.r.squared
  ),
  AIC = c(
    AIC(null_model),
    AIC(final_model)
  ),
  BIC = c(
    BIC(null_model),
    BIC(final_model)
  )
)

kable(discussion_table, digits = 3)


```

```{r}
subset_sum <- summary(subset_fit)

plot_df <- data.frame(
  Predictors = 1:length(subset_sum$adjr2),
  AdjR2 = subset_sum$adjr2,
  BIC = subset_sum$bic
)

best_bic <- which.min(plot_df$BIC)

library(ggplot2)

p1 <- ggplot(plot_df, aes(x = Predictors, y = AdjR2)) +
  geom_line(color = "steelblue", linewidth = 1) +
  geom_point(color = "steelblue", size = 3) +
  labs(
    title = "Adjusted R2 vs # of Predictors",
    x = "# of Predictors",
    y = "Adjusted R-squared"
  ) +
  theme_minimal(base_size = 14)

p2 <- ggplot(plot_df, aes(x = Predictors, y = BIC)) +
  geom_line(color = "darkorange", linewidth = 1) +
  geom_point(color = "darkorange", size = 3) +
  geom_point(data = plot_df[best_bic, ], 
             aes(x = Predictors, y = BIC), 
             color = "red", size = 4) +
  labs(
    title = "BIC vs # of Predictors",
    x = "# of Predictors",
    y = "BIC"
  ) +
  theme_minimal(base_size = 14)

library(gridExtra)
grid.arrange(p1, p2, ncol = 2)
```

```{r}
min_fp <- min(predict_data$FantasyPoints)

log_pred <- predict(final_model, newdata = predict_data)

pred_original <- exp(log_pred) - 1 + min_fp

predict_data$Predicted <- pred_original

library(ggplot2)

ggplot(predict_data, aes(x = Predicted, y = FantasyPoints)) +
  geom_point(alpha = 0.3, color = "steelblue") +
  geom_abline(slope = 1, intercept = 0, color = "red", linewidth = 1) +
    geom_smooth(method = "lm", color = "darkorange", se = FALSE) +
  labs(
    title = "Predicted vs Actual Fantasy Points",
    x = "Predicted Fantasy Points",
    y = "Actual Fantasy Points"
  ) +
  theme_minimal(base_size = 14)
```

```{r}
coef_df <- data.frame(
  term = names(coef(final_model))[-1],
  estimate = coef(final_model)[-1]
)

ggplot(coef_df, aes(x = reorder(term, estimate), y = estimate)) +
  geom_col(fill = "steelblue") +
  coord_flip() +
  labs(
    title = "Effect of Predictors on Fantasy Points (Log Scale)",
    x = "Predictor",
    y = "Coefficient"
  ) +
  theme_minimal()

```

```{r}

predict_data$Error <- abs(predict_data$FantasyPoints - predict_data$Predicted)

ggplot(predict_data, aes(x = Starter, y = Error, fill = Starter)) +
  geom_boxplot() +
  labs(
    title = "Prediction Error by Starter Status",
    x = "Starter",
    y = "Absolute Error"
  ) +
  theme_minimal()
```

```{r}
ggplot(predict_data, aes(x = Predicted, y = FantasyPoints, color = Position)) +
  geom_point(alpha = 0.4) +
  geom_abline(slope = 1, intercept = 0) +
  labs(
    title = "Predicted vs Actual by Position",
    x = "Predicted",
    y = "Actual"
  ) +
  theme_minimal()
```

```{r}
null_model <- lm(FantasyPoints ~ 1, data = predict_data)

discussion_table <- tibble(
  Model = c("Null Model", "Final Model"),
  RMSE = c(
    sqrt(mean((predict_data$FantasyPoints - mean(predict_data$FantasyPoints))^2)),
    sqrt(mean((predict_data$FantasyPoints - predict_data$Predicted)^2))
  ),
  R2 = c(
    0,
    cor(predict_data$FantasyPoints, predict_data$Predicted)^2
  ),
  Adj_R2 = c(
    0,
    summary(final_model)$adj.r.squared
  ),
  AIC = c(
    AIC(null_model),
    AIC(final_model)
  ),
  BIC = c(
    BIC(null_model),
    BIC(final_model)
  )
)

kable(discussion_table, digits = 3)

```

$\text{Fantasy Pts} =\text{Points} + 1.2\text{Rebounds} + 1.5\text{Assists} + 3\text{Steals} + 3\text{Blocks} - \text{Turnovers}$

```{r}
formula(final_model)
coef(final_model)


```

$$
\log(\text{FantasyPoints} - \text{min_fp} + 1) 
= 1.74 + 0.054\,\text{Minutes} + 0.016\,\text{USG}
- 0.091\,\text{Starter}
- 0.174\,\text{PositionF}\\
- 0.230\,\text{PositionG} 
- 0.158\,\text{PositionPF}
- 0.182\,\text{PositionPG}
- 0.210\,\text{PositionSF}
- 0.305\,\text{PositionSG}
$$
