---
title: "STAT 3400 - Homework 1"
author: "Taketo Horigome"
date: "Due January 18, 2026"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
library(tidyverse)
library(knitr)
library(tinytex)

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(out.width = "60%")
```

# Problem 1

For each of the scenarios below, indicate whether we would generally expect the performance of a flexible statistical learning method to be better or worse than an inflexible method. Explain your answer.

## Part A

The sample size $n$ is extremely large, and the number of predictors $p$ is small.

### Solution:

Since the smaple size is extremly large and the number of predictors is small, a flexible statistical method will generallu perform better. When the trainig dataset is large enough, flexible models can learn more complex patterns without severe overfitting. Because $p$ is small, the risk of overfitting is also reduced. In contrast, an inflexible model may have higher bias and may not fully capture the underlying relationship in the data. 

## Part B

The number of predictors $p$ is extremely large, and the number of observations $n$ is small.

### Solution:

In this scenario, an inflexible model is likely to perform better than a flexible one. Since the number of observations is small relative to the number of predictors, flexible models can easily overfit the training data. An inflexible model helps control variance and is less sensitive to noise when data is limited. 

## Part C

The relationship between the predictors and response is highly nonlinear.

### Solution:

When the relationship between the predictors and the response is highly nonlinear, a flexible model tends to perform better. Flexible modles are able to capture nonlinear trends, while inflexible models, which often assume a linear relationship, may fail to represent the true pattern in the data and therefore have high bias. 


## Part D

The variance of the error terms (i.e. $\sigma^2=\text{Var}(\epsilon)$), is extremely high.

### Solution:

When the variance of the error terms is extremely high, an inflexible model will generally perform better. In this case, flexible models are more likely to fit the noise in the data, leading to overfitting and high variance. Inflexible models are more robust to noise and therefore tend to genralize better under high erro variance. 

# Problem 2

Explain whether each scenario is a classification or regression problem, and indicate whether we are most interested in inference or prediction. Finally, provide $n$ and $p$.

## Part A

We collect a set of data on the top 500 firms in the US. For each firm we record profit, number of employees, industry and the CEO salary. We are interested in understanding which factors affect CEO salary.

### Solution:

This is a regression problem since CEO salary is a continuous numerical vairable. We are mainly interested in inference, because the goal is to understand which factors affect CEO salary. The number of observations is $n = 500$ firms, and the number of predictors is $p = 3$, which contains profit, number of employees, and industry. 

## Part B

We are considering launching a new product and wish to know whether it will be a success or a failure. We collect data on 20 similar products that were previously launched. For each product we have recorded whether it was a success or failure, price charged for the product, marketing budget, competition price, and ten other variables.

### Solution:
This is a classification problem since the outcome is whether the product is a success or a failure. We are more interested in prediction, because the goal is to predict the outcome for a new product. The number of observations is $n = 20$ products, and the number of predictors is $p = 13$, which contains price, marketing budget, competition price, and ten other variables. 

## Part C

We are interested in predicting the % change in the USD/Euro exchange rate in relation to the weekly changes in the world stock markets. Hence we collect weekly data for all of 2025. For each week we record the % change in the USD/Euro, the % change in the US market, the % change in the British market, and the % change in the German market.

### Solution:

This is a regression problem, since the response varialbe is the percentage change in the USD/EURO exchange rate, which is continuous. We are interested in prediction, as the goal is to predict future exchage-rate changes. The number of observations is $n = 52$ weeks, and the number of predictors is $p = 3$ which contains the percentage changes in the US, British, and the German markets. 

# Problem 3

Describe the differences between a parametric and a nonparametric statistical learning approach. What are the advantages of a parametric approach to regression or classification (as opposed to a nonparametric approach)? What are its disadvantages?

### Solution:

A parametric statistical learning approach assumes a specific functional form for the relationship between predictors and the response, such as a linear model. This means we estimate a fixed number of parameters. A nonparametric approach does not assume a specific functional form and instead allows the model structure to be determined more flexibly from the data. 
The main advantages of parametric methods are that they usually require fewer observations, are computationally efficient, and are easier to interpret. They also tend to have lower variance. 
The main disadvantages are the if the assumed model form is incorrect, parametric methods can have high bias and perform poorly when the relationship is complex or nonlinear. 

# Problem 4

Describe two real-world problems that require supervised statistical learning methods and two problems that require unsupervised methods. Why is each example supervised versus unsupervised?

### Solution:

One real-world problem that requires supervised statistical learning is stock price prediction, where past prices and financial indicators are used to predict future prices. This is supervised because historical price labels ar eavailable. Another example is predicting the winner of a soccer league using past match data, where the outcomes are known in the training data. 
Examples of unsupervised learning include grouping airline customers to determine what types of promotions migh increase usage. This is unsupervised because there are no predefined customer categories. Another example is clustering species based on observed characteristics, where the species lables are unknown and the goal is to discover natural groupings in the data. 